SET NAMES UTF8;
DROP DATABASE IF EXISTS skq;
CREATE DATABASE skq CHARSET=UTF8;
USE skq;
CREATE TABLE skq_user(
    uid INT PRIMARY KEY AUTO_INCREMENT,
    uname VARCHAR(32),
    upwd VARCHAR(32),
    phone VARCHAR(16)
);
INSERT INTO skq_user VALUES
(NULL,'上海店',md5('123'),'13512345678');